server:
    port: 8778

debug: true

spring:
    cloud:
        zookeeper:
            connectString: 127.0.0.1:2181
            enabled: false
    sleuth:
        enabled: false

swagger:
    basePackage: com.myfirstapp.cloud.controller
    title: ctg-myfirstapp-cloud RESTful APIs
    description: ctg-myfirstapp-cloud RESTful API
    version: 1.0.0-SNAPSHOT
    openApi:
        group: OpenApi
        basePackage: com.myfirstapp.cloud.controller
        title: actg-myfirstapp-cloud Open APIs
        description: ctg-myfirstapp-cloud Open API
        version: 1.0.0-SNAPSHOT
